# remove "-disabled" from the folder name for pdf compilation via github actions

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
        env:
          TARGET_NAME: ${{ github.event.repository.name }}--${{ steps.extract_branch.outputs.branch }}
      - name: Upload PDF file
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.event.repository.name }}--${{ steps.extract_branch.outputs.branch }}
          path: |
            *.pdf
            answers-*-*.csv